# Generated by Django 5.1.6 on 2025-05-11 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001__'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredshelf',
            name='shelf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discovery_features', to='library.shelf'),
        ),
    ]
